### ISSUE TITLE
du_aod550 seems to be coming from climatology

### ISSUE THREAD

**Issue by bbakernoaa** [ufs-community/CATChem#4]
In looking at the PR #3 there is an issue with the diagnostic du_aod550.  It seems constant in time although visually not showing any transport. 

At time 0 
![image](https://github.com/ufs-community/CATChem/assets/22104759/99f5f999-103e-42f8-a246-169116d18b71)

At time 15 days 
![image](https://github.com/ufs-community/CATChem/assets/22104759/3549215f-c156-4dbd-9655-0fec6d2b14b5)

**Comment by zhanglikate** [comment]
I just finished testing a run using the model spin-up results as ICs
instead of MERRA-2, which shows lower biases than using MERRA-2, but still
has similar high biases over African areas.

Kate

**Comment by bbakernoaa** [comment]
@zhanglikate The issue is that the dust isn't changing in time.  We should be able to see the transport here.  We aren't looking at bias here.

**Comment by zhanglikate** [comment]
You meant in Juan’s PR runs? Did you update the dust scheme ?

Kate

**Comment by bbakernoaa** [comment]
@zhanglikate Yes this is from Jian's PR.  I did nothing with the dust scheme yet so it should be the same/similar to what was in your fork. This is just using her codebase from the PR.

**Comment by zhanglikate** [comment]
For dust AOD, the CCPP-Chem results are identical as UFS-aerosols in the
S2S runs, you may also check the S2S results of these two models about the
dust results, including concentration and AOD, I can forward the results
paths to you.

Kate

**Comment by bbakernoaa** [comment]
I understand that the CCPP-Chem results may look identical.  The issue is that we need the CATChem results from #3  to look correct.  All other species look fine except dust.

**Comment by zhanglikate** [comment]
Also, the output file looks strange to me. We normally output the results
every 6 hours, how can you archive all the output steps in one file? I am a
little bit concerning the way of the PR run, which is as what I saw in the
workflow runs about the temporal variation.

Kate

**Comment by bbakernoaa** [comment]
This isn't archived into a single file.  I just opened them with ncview. `ncview` has the ability to open multiple files at once and if they have the correct netcdf attributes in time (ie CF convention) then it will process the time stamps and stack them correctly.  

`ncview gfs*sfcf*.nc`

**Comment by zhanglikate** [comment]
How about the dust concentration, did you see any changes at these times?

Kate

**Comment by bbakernoaa** [comment]
The dust concentration itself does change.  Looking at dust4 in the sfc 

time 0 
![image](https://github.com/ufs-community/CATChem/assets/22104759/5c1c39ec-0abd-4352-b89e-7e9e02ef808d)

time +15 days 
![image](https://github.com/ufs-community/CATChem/assets/22104759/ff6345f9-eeb7-45f3-9bef-a2fa0840373e)

**Comment by zhanglikate** [comment]
Other than the model output of 550  dustAOD, did you have the UPP output of dust AOD? Thanks.

Kate

**Comment by bbakernoaa** [comment]
I didn't run post.  This is just the diagnostic du_dust550 written to the sfc files

**Comment by zhanglikate** [comment]
> This is still an issue. If prognostic aerosols are used we need to put this into a different name then. The other species seem to be using the prognostic as the oc_aod550 for example moves with time but the du_aod550 does come from the climatology as you mentioned.
> 
> I did test using the `iaer=2011` and that seems to be working properly

@bbakernoaa I am really confused with the issue you mentioned. May I know more details about the issue? The GFS online look-up table will calculate the AOD with two options, 1) iaer=1011, 2)iaer=2011, this two potions will never be turned on at the same time. So no matter oc_aod550 or du_aod550 , or other species, their output of AOD would only be  1) iaer=1011 or 2)iaer=2011. If you are using 1) iaer=1011, the AOD from the model output will be from the MARRA-2 climatological aerosol data, however using the online RH. Even you still have the prognostic aerosols coupled with the ATM model, but the prognostic aerosols concentration will not be used as aerosols feedback in the GFS online AOD calculation, which means that there is no aerosol feedback from the online aerosols model, just come from the MARRA-2 climatological data. If you are using 2) iaer=2011, which means the prognostic aerosols concentration from the online coupled aerosol model will be used to calculate the aerosols feedback and the GFS AOD model output for each species at 550nm. I don't see there is an issue as you described. 

If you would like to have more detailed discussion, better to set up a google meeting. This way is consistent as current UFS-Aerosols model, nobody change it in CATChem. Thanks.

**Comment by zhanglikate** [comment]
@bbakernoaa Even for iaer=1011, they are not content, because the MERRA2 is just the aerosol concentration. RH need to consider for AOD. You meant you set iaer=1011 and iaer=2011, they are the same for AOD 550 nm model output?
